package com.kou.entity;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.user
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.age
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.user
     *
     * @return the value of test.user
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.user
     *
     * @param user the value for test.user
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.age
     *
     * @return the value of test.age
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.age
     *
     * @param age the value for test.age
     *
     * @mbggenerated Tue Sep 05 14:41:09 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}